// src/features/loom/constants/loom-themes.ts
import { Headphones, ShoppingBag, Gamepad2, Radio, FileText, Globe } from "lucide-react";
import type { LoomTheme } from "../types/loom.types";

export const LOOM_THEMES: Record<string, LoomTheme> = {
  artisanal: {
    id: "artisanal",
    name: "Himalayan Artisanal",
    badge: "Handcrafted Texture Series",
    title: "The Himalayan Artisanal Theme",
    desc: "Grounded in natural Lokta paper textures, warm valley terracotta borders, baked clay buttons, and marigold accents. Tailored for heritage storytellers, visual artists, and folk musicians.",
    specs: [
      "Subtle embossed Newari brick filigree pattern",
      "Marigold celebratory tipping micro-animations",
      "Lokta fiber paper parchment container fills",
    ],
    cardClass: "bg-surface-container-lowest border-2 border-primary-container/60 shadow-xl",
    headerAccentClass: "text-primary",
    primaryActionClass: "bg-primary-container text-on-primary",
    creatorName: "Purna Nepali",
    creatorHandle: "nudge.np/@purnanepali",
    creatorBio: "Reviving Gandharva folk strings for modern film soundtracks.",
    tile1Text: "Listen: 'Mustang Reverie' (EP)",
    tile1Icon: Headphones,
    tile3Text: "Hand-carved Lokta Sheet Music Book",
    tile3Icon: ShoppingBag,
  },
  cyber: {
    id: "cyber",
    name: "Cyber Pokhara",
    badge: "Neon Lakefront Streamer",
    title: "The Cyber Pokhara Theme",
    desc: "High-contrast dark-mode canvas accented with Fewa Lake neon cyans and electric marigold. Built for gaming streamers, tech reviewers, and digital motion animators.",
    specs: [
      "OLED pure black card surface with cyan glow borders",
      "Twitch & YouTube direct live-stream ticker integration",
      "Digital cyberpunk geometric HUD typography",
    ],
    cardClass: "bg-[#181615] text-white border-2 border-cyan-500/80 shadow-[0_0_25px_rgba(6,182,212,0.15)]",
    headerAccentClass: "text-cyan-400",
    primaryActionClass: "bg-cyan-500 text-black font-bold",
    creatorName: "Avishek Gurung",
    creatorHandle: "nudge.np/@avishek_live",
    creatorBio: "Pokhara Valorant & PUBG Pro • Daily 8 PM Live Stream 🎮",
    tile1Text: "Join My Discord Server (8,400+ Gamers)",
    tile1Icon: Gamepad2,
    tile3Text: "Custom Nepali Gaming PC Specs 2026",
    tile3Icon: Radio,
  },
  minimalist: {
    id: "minimalist",
    name: "Minimalist Storyteller",
    badge: "Editorial Clean Series",
    title: "The Minimalist Storyteller Theme",
    desc: "Refined Scandinavian clarity meets high-legibility serif typography. Generous negative space designed for long-form journalists, essayists, and minimalist architects.",
    specs: [
      "Razor-thin monochrome border lines (1px #E6E1DA)",
      "Subdued, distraction-free typographic hierarchy",
      "Substack & Medium publication feed embeds",
    ],
    cardClass: "bg-white text-zinc-900 border border-zinc-300 shadow-sm",
    headerAccentClass: "text-zinc-900",
    primaryActionClass: "bg-zinc-900 text-white font-semibold",
    creatorName: "Dr. Alisha Karki",
    creatorHandle: "nudge.np/@alishakarki",
    creatorBio: "Writing about Himalayan climate policy, water security & architecture.",
    tile1Text: "Read: 'Glacial Retreat in Solukhumbu'",
    tile1Icon: FileText,
    tile3Text: "Subscribe to My Sunday Climate Dispatch",
    tile3Icon: Globe,
  },
};
