// Merge this into the `theme.extend` block of your tailwind.config.ts.
// Pulled directly from the original design so class names like
// `bg-primary-container`, `text-on-surface`, `font-headline-sm` resolve.

export const nudgeThemeExtend = {
  colors: {
    "error-container": "#ffdad6",
    "surface-container-low": "#faf3e5",
    "surface-bright": "#fff9ed",
    "on-tertiary-container": "#c3fee1",
    "on-secondary-fixed": "#281900",
    "on-tertiary-fixed-variant": "#17503b",
    "surface-dim": "#e0d9cc",
    "outline-variant": "#dfc0b7",
    "on-secondary": "#ffffff",
    "surface-tint": "#a83914",
    "primary-fixed": "#ffdbd1",
    "on-error-container": "#93000a",
    "surface-container-highest": "#e8e2d5",
    "on-error": "#ffffff",
    "on-surface-variant": "#58423b",
    "on-tertiary": "#ffffff",
    tertiary: "#285f49",
    surface: "#fff9ed",
    "on-secondary-container": "#714d00",
    "secondary-fixed": "#ffdead",
    "tertiary-fixed-dim": "#9ad3b7",
    "primary-fixed-dim": "#ffb59f",
    "on-surface": "#1e1c13",
    "inverse-on-surface": "#f7f0e2",
    "on-primary": "#ffffff",
    "surface-container": "#f4ede0",
    "secondary-container": "#fdbe50",
    "on-background": "#1e1c13",
    "surface-variant": "#e8e2d5",
    background: "#fff9ed",
    "on-primary-container": "#ffede8",
    "surface-container-lowest": "#ffffff",
    "surface-container-high": "#eee8da",
    "tertiary-fixed": "#b5efd3",
    "on-tertiary-fixed": "#002115",
    "on-primary-fixed-variant": "#862300",
    secondary: "#7e5700",
    "inverse-surface": "#333027",
    "on-secondary-fixed-variant": "#604100",
    outline: "#8c716a",
    primary: "#9b2f0a",
    "primary-container": "#bc4722",
    "tertiary-container": "#427861",
    "secondary-fixed-dim": "#fabc4d",
    "inverse-primary": "#ffb59f",
    error: "#ba1a1a",
    "on-primary-fixed": "#3a0a00",
  },
  spacing: {
    "space-md": "1rem",
    "space-sm": "0.75rem",
    "margin-tablet": "2rem",
    "space-lg": "1.5rem",
    "space-3xl": "4.5rem",
    "space-xs": "0.5rem",
    "margin-desktop": "4rem",
    "space-2xl": "3rem",
    "space-xl": "2rem",
    gutter: "1.25rem",
    "gutter-desktop": "2rem",
    "space-2xs": "0.25rem",
    margin: "1rem",
  },
  fontFamily: {
    "headline-sm": ["Epilogue"],
    "display-hero-mobile": ["Epilogue"],
    "body-lg": ["Plus Jakarta Sans"],
    "display-hero": ["Epilogue"],
    "headline-md": ["Epilogue"],
    "label-sm": ["Plus Jakarta Sans"],
    "label-md": ["Plus Jakarta Sans"],
    "headline-lg": ["Epilogue"],
    "body-md": ["Plus Jakarta Sans"],
    "body-sm": ["Plus Jakarta Sans"],
    "title-md": ["Plus Jakarta Sans"],
  },
  fontSize: {
    "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
    "display-hero-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.015em", fontWeight: "700" }],
    "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
    "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
    "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
    "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
    "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
    "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
    "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
    "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
    "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
  },
};
